# Generated by Django 4.2.6 on 2023-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_status', models.CharField(choices=[('WFO', 'Work From Office'), ('WFH', 'Work From Home')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
